name: Deploy Auth

on:
  push:
    branches: [prod]
    paths:
      - 'auth/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: auth

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: npm install && npm run build
      
      - name: List directory
        run: ls -la

      # - name: Deploy
      #   uses: SamKirkland/FTP-Deploy-Action@4.3.0
      #   with:
      #     server: ${{secrets.PROD_HOST_IP}}
      #     username: ${{secrets.PROD_HOST_USER_NAME}}
      #     password: ${{secrets.PROD_HOST_PASSWORD}}
      #     local-dir: ./dist/
      #     server-dir: /auth/
