name: Deploy Container

on:
  push:
    branches: [main,prod]
    paths:
      - 'container/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build And Deploy
        uses: actions/checkout@v2

      - name: Build and deploy
        env:
          IP_ADDRESS: ${{ secrets.PROD_HOST_IP }}
          USER_NAME: ${{ secrets.PROD_HOST_USER_NAME }}
          PASSWORD: ${{ secrets.PROD_HOST_PASSWORD }}
          PRODUCTION_DOMAIN: ${{ secrets.PROD_BASE_DOMAIN }}
        run: npm install && npm run build && npm run prod-deploy
      
      - name: Purge index.html
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.PROD_CDN_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.PROD_CDN_TOKEN }}
          PURGE_URLS: '["${{ secrets.PROD_BASE_DOMAIN }}/container/index.html"]'
