name: Deploy Marketing

on:
  push:
    #branches:
    #  - prod
    paths:
      - 'marketing/**'

defaults:
  run:
    working-directory: marketing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and deploy
        env:
          IP_ADDRESS: ${{ secrets.PROD_HOST_IP }}
          USER_NAME: ${{ secrets.PROD_HOST_USER_NAME }}
          PASSWORD: ${{ secrets.PROD_HOST_PASSWORD }}
        run: npm install && npm run build && npm run prod-deploy
